---

# Main tasks file for flink role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::flink'
    - 'role::flink::init'
